unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s

set -g mouse on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set -g base-index 1              # start indexing windows at 1 instead of 0
# set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top 


# Catpuccin Configs
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
# set -g status-left ""
set -g status-left "#{E:@catppuccin_status_user}"
set -g status-justify centre

set -g status-right "#{E:@catppuccin_status_host}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set-option -g allow-rename off
set-window-option -g automatic-rename off


# Start pane numbering at 1
set -g pane-base-index 1

set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"
set -g @catppuccin_window_text " #{window_name}"

# Transient configs
set -g @transient-status-delay '0.5'
set -g @transient-status-stall '120'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
# set -g @plugin 'tmux-plugins/tmux-sidebar'
# set -g @plugin 'tardunge/tmux-gh'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'thesast/tmux-transient-status'
set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

run '~/.tmux/plugins/tpm/tpm'

