# New way to see and navigate directory trees
brew "broot"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Interactive git commands in the terminal
brew "forgit"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# AI-powered command-line workflow tool for developers
brew "qwen-code"
# Cross-shell prompt for astronauts
brew "starship"
# Shell extension to navigate your filesystem faster
brew "zoxide"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "angular.ng-template"
vscode "arjun.swagger-viewer"
vscode "asciidoctor.asciidoctor-vscode"
vscode "atlassian.atlascode"
vscode "blackboxapp.blackbox"
vscode "catppuccin.catppuccin-vsc"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "github.github-vscode-theme"
vscode "gruntfuggly.todo-tree"
vscode "ipatalas.vscode-postfix-ts"
vscode "johnpapa.angular2"
vscode "letmaik.git-tree-compare"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "pkief.material-icon-theme"
vscode "rangav.vscode-thunder-client"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ryanluker.vscode-coverage-gutters"
vscode "sandcastle.vscode-open"
vscode "sandipchitale.docker-dive"
vscode "sonarsource.sonarlint-vscode"
vscode "streetsidesoftware.code-spell-checker"
vscode "ultram4rine.vscode-choosealicense"
vscode "usernamehw.errorlens"
vscode "vmware.vscode-boot-dev-pack"
vscode "vmware.vscode-spring-boot"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscjava.vscode-spring-boot-dashboard"
vscode "vscjava.vscode-spring-initializr"
vscode "wakatime.vscode-wakatime"
vscode "wallabyjs.quokka-vscode"
vscode "wmaurer.change-case"
vscode "zhuangtongfa.material-theme"
vscode "zignd.html-css-class-completion"
flatpak "md.obsidian.Obsidian"
npm "corepack"
npm "oclif"
npm "tailwindcss"
